### ISSUE TITLE
PII/Banned Terms - Todo List

### ISSUE THREAD

**Issue by ash0ts** [soumik12345/guardrails-genie#7]
- [ ] Add streamlit field for custom patterns for RegexModels
- [ ] Add streamlit field for allowing returning of detected entities
- [ ] Add streamlit field for allowing of anonymization
- [ ] Add streamlit field for Banned Terms/Company names for LLMEntityModel
- [ ] Reduce tech debt of entity models by creating a common class and response model as all are made identically as is
- [ ] Add eval of banned words guardrails
- [ ] Fix and weaveify PII benchmark

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Added streamlit fields for custom patterns, returning detected entities, anonymization, and banned terms for entity recognition guardrails. Also added evaluation of banned words guardrails.

You can review changes in this commit: https://github.com/mnmnk43434/soumik12345-guardrails-genie-7/commit/b1a38bbf7d5f1823f9f07823ff18771368d879fb.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
